// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvpoqyklxclygwggryxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cG9xeWtseGNseWd3Z2dyeXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDk3NjQsImV4cCI6MjA2NTgyNTc2NH0.Zq2mrhgweSpe2Bp2sfrx7V1PS3vi4O-CyRSTjiqbE3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);